/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ItemsSearchRouteImport } from './routes/items-search'
import { Route as CreateItemRouteImport } from './routes/create-item'
import { Route as IndexRouteImport } from './routes/index'

const ItemsSearchRoute = ItemsSearchRouteImport.update({
  id: '/items-search',
  path: '/items-search',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateItemRoute = CreateItemRouteImport.update({
  id: '/create-item',
  path: '/create-item',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-item': typeof CreateItemRoute
  '/items-search': typeof ItemsSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-item': typeof CreateItemRoute
  '/items-search': typeof ItemsSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-item': typeof CreateItemRoute
  '/items-search': typeof ItemsSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-item' | '/items-search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-item' | '/items-search'
  id: '__root__' | '/' | '/create-item' | '/items-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateItemRoute: typeof CreateItemRoute
  ItemsSearchRoute: typeof ItemsSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/items-search': {
      id: '/items-search'
      path: '/items-search'
      fullPath: '/items-search'
      preLoaderRoute: typeof ItemsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-item': {
      id: '/create-item'
      path: '/create-item'
      fullPath: '/create-item'
      preLoaderRoute: typeof CreateItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateItemRoute: CreateItemRoute,
  ItemsSearchRoute: ItemsSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
